version: "3"
name: "nest-urlify"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: urlify
      POSTGRES_USER: user
      POSTGRES_PASSWORD: UHgxTCauZrqf
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local
  backend:
    build: .
    environment:
      PORT: 2000
      DATABASE_HOST: postgres
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: UHgxTCauZrqf
      DATABASE_NAME: urlify
      JWT_SECRET: fWxvvXgXkA9W
    depends_on:
      - postgres
    networks:
      - local
  frontend:
    build: ./web
    depends_on:
      - postgres
    ports:
      - "80:80"
      - "443:443"
    networks:
      - local
  pgadmin4:
    image: elestio/pgadmin:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: user@mail.ru
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - local

networks:
  local:
    driver: bridge
